USE SAKILA;
SELECT * FROM ACTOR,FILM,CUSTOMER;
SELECT * FROM FILM_TEXT;
SELECT DISTINCT NAME AS LANGUAGE FROM LANGUAGE;
SELECT DISTINCT STORE_ID FROM STORE;
SELECT COUNT (STAFF_ID) FROM STAFF;
SELECT FIRST_NAME FROM STAFF
